Import ('env')

name = 'counterclient'
inc = env.Dir('.')
deps = ['fud_client', 'getoptpp', 'mili']

src = env.Glob('*.cpp') 
src.remove(env.File('counter_client.cpp'))
env.CreateObject('counterclient-objects', inc, src, deps)

deps = list(deps) + ['counterclient-objects']
env.CreateProgram(name, inc, ['counter_client.cpp'], deps)