Import ('env')

# Issue XYZ
# Delete the next line when issue is corrected.
env.Append(LINKFLAGS='-Wl,-rpath=/usr/local/lib')

name = 'counterclient'
inc = env.Dir('.')
src = env.Glob('*.cpp')
deps = ['fud_client', 'getoptpp', 'mili']
env.CreateProgram(name, inc, src, deps)