Import ('env')

# Issue XYZ
# Delete the next line when issue is corrected.
env.Append(LINKFLAGS='-Wl,-rpath=/usr/local/lib')

name = 'counterserver'
inc = env.Dir('.')
src = env.Glob('*.cpp') 
deps = ['fud_server', 'getoptpp', 'mili']
env.CreateProgram(name, inc, src, deps)