Import ('env')

# Issue XYZ
# Delete the next line when issue is corrected.
env.Append(LINKFLAGS='-Wl,-rpath=/usr/local/lib')

name = 'countermsgserver'
inc = env.Dir('.')
deps = ['fud_server', 'fud_client', 'getoptpp', 'mili']

src = env.Glob('*.cpp') 
src.remove(env.File('counter_main.cpp'))
env.CreateObject('countermsgserver-objects', inc, src, deps)

deps = list(deps) + ['countermsgserver-objects']
env.CreateProgram(name, inc, ['counter_main.cpp'], deps)