Import ('env')

name = 'fscclient'
inc = env.Dir('.')
deps = ['fud_client', 'getoptpp', 'mili']

src = env.Glob('*.cpp') 
src.remove(env.File('counter_client.cpp'))
env.CreateObject('fscclient-objects', inc, src, deps)

deps = list(deps) + ['fscclient-objects']
env.CreateProgram(name, inc, ['counter_client.cpp'], deps)